### ISSUE TITLE
Trouble configuring postgres

### ISSUE THREAD

**Issue by MarkEstefanos** [RunestoneInteractive/thinkcspy#36]
I'm running into errors trying to self host this with a working database. 

I've configured postgres and created a database and user for runestone,  and I'm not sure what to do from here.

Here's the error I'm getting when i try `runestone build`:
```
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/runestone", line 7, in <module>
    from runestone.__main__ import main
  File "/home/ubuntu/.local/lib/python2.7/site-packages/runestone/__init__.py", line 1, in <module>
    from .activecode import *
  File "/home/ubuntu/.local/lib/python2.7/site-packages/runestone/activecode/__init__.py", line 1, in <module>
    from .activecode import *
  File "/home/ubuntu/.local/lib/python2.7/site-packages/runestone/activecode/activecode.py", line 26, in <module>
    from runestone.server.componentdb import addQuestionToDB, addHTMLToDB
  File "/home/ubuntu/.local/lib/python2.7/site-packages/runestone/server/componentdb.py", line 30, in <module>
    questions = Table('questions', meta, autoload=True, autoload_with=engine)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 439, in __new__
    metadata._remove_table(name, schema)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 434, in __new__
    table._init(name, metadata, *args, **kw)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 514, in _init
    include_columns, _extend_on=_extend_on)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 527, in _autoload
    _extend_on=_extend_on
  File "/home/ubuntu/.local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2045, in run_callable
    return conn.run_callable(callable_, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1534, in run_callable
    return callable_(self, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 372, in reflecttable
    table, include_columns, exclude_columns, **opts)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/sqlalchemy/engine/reflection.py", line 598, in reflecttable
    table_name, schema, **table.dialect_kwargs):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/sqlalchemy/engine/reflection.py", line 369, in get_columns
    **kw)
  File "<string>", line 2, in get_columns
  File "/home/ubuntu/.local/lib/python2.7/site-packages/sqlalchemy/engine/reflection.py", line 54, in cache
    ret = fn(self, con, *args, **kw)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/sqlalchemy/dialects/postgresql/base.py", line 2397, in get_columns
    info_cache=kw.get('info_cache'))
  File "<string>", line 2, in get_table_oid
  File "/home/ubuntu/.local/lib/python2.7/site-packages/sqlalchemy/engine/reflection.py", line 54, in cache
    ret = fn(self, con, *args, **kw)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/sqlalchemy/dialects/postgresql/base.py", line 2323, in get_table_oid
    raise exc.NoSuchTableError(table_name)
sqlalchemy.exc.NoSuchTableError: questions
```

Looks like I need to further configure the database, but I can't find a script or guide to do that in any of the repos.

Thanks for the help!

**Comment by bnmnetp** [comment]
I think I may have already answered this for you in another forum, but for posterity.

The answer to this is that after you have started runestone you need to at least access the main page one time to get all of the tables created.  Just starting, does not cause all the model files to load and create their tables. 

I have updated the README accordingly.
